import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const binary=join(root,"server/target/release",process.platform==="win32"?"mario-server.exe":"mario-server");
if(!existsSync(binary)||!existsSync(join(root,"client/dist/index.html")))throw Error("请先运行 npm run web:build");
for(const key of ["DATABASE_URL","MARIO_MASTER_KEY"])if(!process.env[key])throw Error(`请配置 ${key}；参见 docs/self-hosting.md`);
const port=process.env.MARIO_PORT??"4217";
console.log(`Web 地址：http://${process.env.MARIO_HOST??"127.0.0.1"}:${port}；公网请通过 HTTPS 反向代理访问`);
const child=spawn(binary,["--port",port],{cwd:root,env:{...process.env,MARIO_WEB_DIR:join(root,"client/dist")},stdio:"inherit"});
child.on("error",error=>{console.error(error.message);process.exitCode=1;});
child.on("exit",code=>{process.exitCode=code??0;});
for(const signal of ["SIGINT","SIGTERM"])process.on(signal,()=>child.kill(signal));
